name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate GitHub Contribution Snake

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: selrahcsan
          outputs: |
            ./dist/github-contribution-grid-snake.svg

      - name: Commit e Push do resultado
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: 'Gerando snake contribution grid'
          add: 'dist/github-contribution-grid-snake.svg'

      - name: Publicar em branch "output"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
